### ISSUE TITLE
Dependency issues are raised when I try to use Mujoco-210

### ISSUE THREAD

**Issue by gr8joo** [buoyancy99/unsup-3d-keypoints#1]
Hi Boyuan,
Thank you for your insightful work along with providing your implementation in public!

I found before that your code works like a charm when I used my paid Mujoco-200.
Although it is expired now, Mujoco has recently released their license for free whose version is 2.1.0 or higher.

I tried to use Mujoco-2.1.x by modifying the line 23 in requirements.txt (mujoco-py==2.0.2.13) to mujoco-py==2.1.2.14, and what I observed is 'mujoco-py==2.1.2.14' conflicts to 'git+git://github.com/buoyancy99/metaworld@unsup-3d-keypoints', the line 48 in requirements.txt as below:

```
ERROR: Cannot install -r requirements.txt (line 48) and mujoco-py==2.1.2.14 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested mujoco-py==2.1.2.14
    metaworld 0.0.0 depends on mujoco-py<2.1 and >=2.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

Considering that we should shift to using free-licensed mujoco in the end (since all the paid licenses will be expired),
would you modify requirements.txt (and your related git pages such as the last three lines in the requirement.txt) to support the latest free mujoco (Mujoco-2.1.x)?

Thank you!

**Comment by buoyancy99** [comment]
Hi HyeongJoo,

Thank you for bringing this up. I've just edited the requirements. Can you test it recently when you have time and let know if it works for you? I can close the issue once we confirm it works.

**Comment by gr8joo** [comment]
Thank you for your timely response!

Yeah, thanks to your modification, now it works!

In addition to the change you made, I installed python packages (glew, osmesa) with following commands:
```
conda install -c menpo osmesa
conda install -c conda-forge glew
```

Thank you so much for your careful fixes!
