### ISSUE TITLE
Questions and request about CURL implementation

### ISSUE THREAD

**Issue by gr8joo** [buoyancy99/unsup-3d-keypoints#2]
Hi,
Thank you for your great work and the kind release of your implementation!

Please note that this is not necessarily an issue, but a set of questions and requests.

While trying to carefully reproduce results in the paper, I have some questions regarding CURL experiment setup in the multi-view setting.
Specifically, I have the following 4 questions (and requests) in your CURL implementation:
1. Did you replace SAC with PPO in CURL, the same as other baseline methods?
2. Are image augmentation techniques independently applied to query and key observations?
3. Did you use the momentum encoder to encode key observations?
4. Can you provide your own CURL implementation? (it would be best to resolve all of my questions!)

Thank you!

**Comment by buoyancy99** [comment]
Hi HyeongJoo,

Can you send me an email and cc co-authors with the same content? I will provide answers and assistance over email for questions about the paper.

**Comment by buoyancy99** [comment]
I answered your questions through email. Let's keep github to repo questions only.
