### ISSUE TITLE
Program gets killed while running & Request for CURL baseline

### ISSUE THREAD

**Issue by wwwwwyyyyyxxxxx** [buoyancy99/unsup-3d-keypoints#4]
Hi,
Thank you for your great work and the kind release of your implementation!

However, when I tried to run your code as described in README, the program got "Killed" after running for 10+ hours. Do you have any idea what is going on?

In addition, would you like to share with us the CURL baseline implementation in this framework?

Appreciate your help.

**Comment by buoyancy99** [comment]
Could you post 
1. Error message
2. System spec. CPU model, RAM and GPU model
3. Exact command you used

**Comment by wwwwwyyyyyxxxxx** [comment]
1. Error message is only "Killed". And then the program is killed.
2. CPU:28 cores 112 processors, RAM: 300G, GPU: 3090*2
3. In readme, commands from "Train & Visualize Pybullet Ant with Keypoint3D(Ours)" to "Train 'Close-Box' environment in Meta-world with baselines", 8 commands in total in tmux.
4. In addition, would you like to share with us the CURL baseline implementation in this framework?

**Comment by wwwwwyyyyyxxxxx** [comment]
> Could you post
> 
> 1. Error message
> 2. System spec. CPU model, RAM and GPU model
> 3. Exact command you used

1. Error message is only "Killed". And then the third and fifth program are killed.
2. CPU:28 cores 112 processors, RAM: 300G, GPU: 3090*2
3. Commands in readme from "Train & Visualize Pybullet Ant with Keypoint3D(Ours)" to "Train 'Close-Box' environment in Meta-world with baselines", 8 commands in total in tmux.
4. In addition, would you like to share with us the CURL baseline implementation in this framework?

**Comment by buoyancy99** [comment]
It's likely an out-of-memory error. The program can take a significant amount of RAM to run so running multiple instances will result in "killed" due to unix memory manager. You can probably only run 2-3 instances on your machine at the same time.

For CURL, please email me and cc Deepak. I will send you the code when I am free asap. The code is not cleaned up but I will provide some instruction on running it.
